# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Songblisher
baseurl:        ""
url:            "https://ssonglee.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Song Lee
  url:          https://ssonglee.github.io/
  email:        becky9110@naver.com  
  github:       ssonglee

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/ssonglee/ssonglee.github.io

# pagination
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num/"